CLASS zcl_lab_19_antmu_lion DEFINITION INHERITING FROM ZCL_LAB_18_antmu_animal
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS get_walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_19_antmu_lion IMPLEMENTATION.
  METHOD get_walk.
    rv_walk = 'THE LION WALK'.
  ENDMETHOD.
ENDCLASS.
