CLASS zcl_lab_39_antmu_budget DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_budget ABSTRACT retURNING VALUE(ev_budget) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_39_antmu_budget IMPLEMENTATION.
ENDCLASS.
