CLASS zcl_lab_12_antmu_linux DEFINITION INHERITING FROM zcl_lab_11_antmu_system
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_antmu_linux IMPLEMENTATION.
ENDCLASS.
