CLASS zcl_lab_21_antmu_classroom DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_21_antmu_classroom IMPLEMENTATION.
ENDCLASS.
