CLASS zcl_lab_37_antmu_screen DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  data: screen_type type string.
ENDCLASS.



CLASS zcl_lab_37_antmu_screen IMPLEMENTATION.
ENDCLASS.
