CLASS zcx_lab_56_antmu_no_date DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_lab_56_antmu_no_date IMPLEMENTATION.
ENDCLASS.
